# Generated by Django 6.0.5 on 2026-07-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_suaptoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="suaptoken",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="suaptoken",
            name="scope",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="suaptoken",
            name="token_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
